name: Deploy

on: 
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

permissions:
  id-token: write
  contents: read

env:
  GOPRIVATE: github.com/uphold/*
  CGO_ENABLED: 0
  ECR_REPOSITORY: redis-exporter

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::304610182419:role/github-actions
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v3

      - name: Setup Environment
        id: setup-environment
        run: |
          TAG_SHA_SHORT=$(git rev-parse --short HEAD)
          echo "FULL_REPO_NAME=${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY" >> $GITHUB_ENV
          echo "TAG_SHA_SHORT=${TAG_SHA_SHORT}" >> $GITHUB_ENV

          EXTRA_TAGS="" # Add any extra tags you want to this variable (space delimited)

          # Version tag
          if [[ "${{ github.ref_name }}" =~ ^(v[0-9]+\.[0-9]+\.[0-9]+$) ]]; then
            EXTRA_TAGS+="${BASH_REMATCH[1]} "
          fi

          # Tag with latest if master branch
          if [[ "${{ github.ref_name }}" =~ ^master$ ]]; then
            EXTRA_TAGS+="latest "
          fi

          echo "EXTRA_TAGS=$EXTRA_TAGS" >> $GITHUB_ENV

      - name: Build Image
        id: build-image
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Building image: ${{ env.FULL_REPO_NAME }}:${{ env.TAG_SHA_SHORT }}"
          docker build \
            -t "${{ env.FULL_REPO_NAME }}:${{ env.TAG_SHA_SHORT }}" \
            --build-arg SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" .

          for tag in ${{ env.EXTRA_TAGS }}; do
            echo "Adding extra tag: ${{ env.FULL_REPO_NAME }}:$tag"
            docker tag "${{ env.FULL_REPO_NAME }}:${{ env.TAG_SHA_SHORT }}" "${{ env.FULL_REPO_NAME }}:$tag"
          done

      - name: Push To ECR
        run: |
          echo "Pushing tag: ${{ env.FULL_REPO_NAME }}:${{ env.TAG_SHA_SHORT }}"
          docker push "${{ env.FULL_REPO_NAME }}:${{ env.TAG_SHA_SHORT }}"

          for tag in ${{ env.EXTRA_TAGS }}; do
            echo "Pushing extra tag: ${{ env.FULL_REPO_NAME }}:$tag"
            docker push "${{ env.FULL_REPO_NAME }}:$tag"
          done

      - name: Remove Build Images From Runner
        if: always()
        run: |
          echo "Cleaning tag: ${{ env.FULL_REPO_NAME }}:${{ env.TAG_SHA_SHORT }}"
          docker image rm "${{ env.FULL_REPO_NAME }}:${{ env.TAG_SHA_SHORT }}"

          for tag in ${{ env.EXTRA_TAGS }}; do
            echo "Cleaning extra tag: ${{ env.FULL_REPO_NAME }}:$tag"
            docker image rm "${{ env.FULL_REPO_NAME }}:$tag"
          done

